# Generated by Django 3.1.6 on 2022-03-16 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_auto_20220315_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='blood_type',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='person',
            name='car_make',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='person',
            name='car_range',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='person',
            name='destination_city',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='person',
            name='destination_state',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='person',
            name='kids',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='person',
            name='origination_city',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='person',
            name='origination_state',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='person',
            name='pets',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='person',
            name='prefered_music',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='person',
            name='social',
            field=models.CharField(max_length=64),
        ),
    ]
