# Generated by Django 3.1.6 on 2022-04-27 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0004_apartment_event_tenet'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(default='N/a', max_length=64),
        ),
    ]
